#!/bin/bash

pushd $(dirname $0)/..

HARVESTER_PATH=../harvester
if [ ! -d ${HARVESTER_PATH} ];then
    HARVESTER_PATH=/tmp/harvester
    if [ ! -d ${HARVESTER_PATH} ];then
    git clone --branch master --single-branch --depth 1 https://github.com/rancher/harvester.git /tmp/harvester
    fi
fi

pushd ${HARVESTER_PATH}
source scripts/version
HARVESTER_VERSION=$VERSION
HARVESTER_TAG=$TAG
popd

popd
if [ -n "$(git status --porcelain --untracked-files=no)" ]; then
    DIRTY="-dirty"
fi

COMMIT=$(git rev-parse --short HEAD)
GIT_TAG=${DRONE_TAG:-$(git tag -l --contains HEAD | head -n 1)}

if [[ -z "$DIRTY" && -n "$GIT_TAG" ]]; then
    VERSION=$GIT_TAG
else
    VERSION="${COMMIT}${DIRTY}"
fi

if [ -z "$ARCH" ]; then
    ARCH=$(go env GOHOSTARCH)
fi

SUFFIX="-${ARCH}"

TAG=${TAG:-${VERSION}${SUFFIX}}
REPO=${REPO:-rancher}

if echo $TAG | grep -q dirty; then
    TAG=dev
fi
